### ISSUE TITLE
all services should be restarted once rabbitmq conf has been updated

### ISSUE THREAD

**Issue by 030** [030/ansible-sensu-server#74]
```
- name: be sure rabbitmq.json is copied
  template:
    src: rabbitmq.j2
    dest: "{{ sensu_conf_d }}/rabbitmq.json"
  notify: restart sensu-services
```
