### ISSUE TITLE
As a user I would like to see that the sensu-server is able to store metrics in graphite using a relay

### ISSUE THREAD

**Issue by 030** [030/ansible-sensu-server#88]
https://ianunruh.com/images/mep4/overall.png

use an ansible git role

```
   git:
     repo: https://github.com/sensu-plugins/sensu-plugins-http.git
     dest: /tmp/sensu-plugins-http
     update: yes
```

```
git clone https://github.com/opower/sensu-metrics-relay.git /tmp/sensu-metrics-relay
sudo cp -R /tmp/sensu-metrics-relay/lib/sensu/extensions/* /etc/sensu/extensions
```
